# Stage 1: Build and install dependencies
FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# RUN npm run build

CMD ["npm", "run", "dev"]

# Stage 2: Production image
# FROM nginx:alpine

# COPY --from=build /app/dist /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

# # Stage 3: Testing image
# FROM build AS test

# CMD ["npm", "test"]
