version: '3.9'

services:
  database:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    tty: true
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    depends_on:
      - database

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    ports:
      - 3000:80

  frontend-tests:
    build:
      context: frontend/.
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./frontend:/app
    depends_on:
      - frontend
    entrypoint: ["npm", "test"]
    command: []
    deploy:
      replicas: 0

volumes:
  postgres:
