# Generated by Django 5.0.6 on 2024-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0002_alter_francesinha_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="francesinha",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
