# Generated by Django 5.0.6 on 2024-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0003_alter_francesinha_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="francesinha",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
